#DjangoBB Forum Settings
# Described here: https://bitbucket.org/slav0nic/djangobb/src/a4c0272533a9/djangobb_forum/settings.py
DJANGOBB_FORUM_BASE_TITLE = 'Scratch Forums'
DJANGOBB_PM_SUPPORT = False
DJANGOBB_HEADER = 'Scratch Forums'
DJANGOBB_TAGLINE = ''
DJANGOBB_LOFI_SUPPORT = False
DJANGOBB_REPUTATION_SUPPORT = False
DJANGOBB_ATTACHMENT_SUPPORT = False
DJANGOBB_GRAVATAR_SUPPORT = False
DJANGOBB_DISPLAY_PROFILE_MENU_OPTIONS = False
DJANGOBB_DISPLAY_AVATAR_OPTIONS = False
DJANGOBB_DISPLAY_USERTITLE = False
DJANGOBB_ALLOW_POLLS = False
